-- Add marketing_manager_brief column to business_brand_profile
-- V5.3 Enhancement: Synthesized marketing role instruction for Stage 2
-- Date: June 21, 2026

-- Add the column
ALTER TABLE business_brand_profile 
ADD COLUMN IF NOT EXISTS marketing_manager_brief TEXT;

-- Add comment
COMMENT ON COLUMN business_brand_profile.marketing_manager_brief IS 
'V5.3: Synthesized Danish marketing manager role instruction (~200 words). Combines all brand layers into one clear brief for Stage 2 (post generation). Generated by Business DNA Analyst persona.';

-- Create index for fast Stage 2 lookups
CREATE INDEX IF NOT EXISTS idx_business_brand_profile_marketing_brief 
ON business_brand_profile(business_id) 
WHERE marketing_manager_brief IS NOT NULL;

-- Verify the column was added
SELECT 
  column_name, 
  data_type, 
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_name = 'business_brand_profile' 
  AND column_name = 'marketing_manager_brief';

-- Show sample of existing data
SELECT 
  business_id,
  CASE 
    WHEN marketing_manager_brief IS NOT NULL 
    THEN 'Has brief (' || length(marketing_manager_brief) || ' chars)'
    ELSE 'NULL - needs regeneration'
  END as brief_status
FROM business_brand_profile
LIMIT 10;
