-- CRITICAL MIGRATION FIXES
-- Apply these in Supabase SQL Editor to fix schema drift
-- Date: 2026-06-29
-- Run in this exact order (dependency sequence)

-- ========================================
-- 1. businesses table columns
-- ========================================

-- Add local_location_reference (e.g., "ved åen", "i Latinkvarteret")
-- Used by: brand-profile-generator-v5, ai-enhance, get-quick-suggestions
ALTER TABLE businesses
ADD COLUMN IF NOT EXISTS local_location_reference TEXT;

COMMENT ON COLUMN businesses.local_location_reference IS 
  'Human-friendly location reference in local language (e.g., "ved åen", "i centrum"). Used for contextual content generation.';

-- Add business_type_hybrid (replaces old vertical system)
-- Used by: get-quick-suggestions, context-fetcher
ALTER TABLE businesses 
ADD COLUMN IF NOT EXISTS business_type_hybrid JSONB;

COMMENT ON COLUMN businesses.business_type_hybrid IS 
  'Hybrid business type classification: {primary: string, secondary: string[], hybridLabel?: string, cuisineType?: string, conceptTags?: string[]}';

-- ========================================
-- 2. business_brand_profile table columns
-- ========================================

-- Add location_strategy (NEW V5.2 - June 25, 2026)
-- Used by: brand-profile-generator-v5 (ACTIVELY WRITING TO THIS)
ALTER TABLE business_brand_profile
ADD COLUMN IF NOT EXISTS location_strategy JSONB DEFAULT NULL;

COMMENT ON COLUMN business_brand_profile.location_strategy IS 
  'V5 location-based marketing strategy including reachable demographics and positioning. Generated by brand-profile-generator-v5.';

-- ========================================
-- 3. business_programme_profiles table columns
-- ========================================

-- Add meal_periods (used for audience segmentation)
ALTER TABLE business_programme_profiles 
ADD COLUMN IF NOT EXISTS meal_periods text[] DEFAULT '{}';

COMMENT ON COLUMN business_programme_profiles.meal_periods IS 
  'Meal periods this programme covers based on time window overlap (60-min minimum). Values: morgenmad, brunch, frokost, eftermiddag, aftensmad, natbar. Derived automatically from time_windows.';

-- Add day_pattern (used for audience segmentation)
ALTER TABLE business_programme_profiles 
ADD COLUMN IF NOT EXISTS day_pattern text;

COMMENT ON COLUMN business_programme_profiles.day_pattern IS 
  'Operating day pattern derived from operating_days. Values: all_week, weekday, weekend, weekend_heavy. Used for audience segmentation.';

-- menu_results_v2_id was already applied manually (✅ FIXED)

-- ========================================
-- 4. Create indexes for new columns
-- ========================================

CREATE INDEX IF NOT EXISTS idx_businesses_local_location_reference 
ON businesses(local_location_reference) WHERE local_location_reference IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_business_brand_profile_location_strategy 
ON business_brand_profile USING GIN (location_strategy) WHERE location_strategy IS NOT NULL;

-- ========================================
-- 5. Verification queries
-- ========================================

-- Run these to verify columns were added:
DO $$
BEGIN
  -- Check businesses columns
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'businesses' 
    AND column_name IN ('local_location_reference', 'business_type_hybrid')
  ) THEN
    RAISE NOTICE '✅ businesses table columns added successfully';
  END IF;
  
  -- Check business_brand_profile columns
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'business_brand_profile' 
    AND column_name = 'location_strategy'
  ) THEN
    RAISE NOTICE '✅ business_brand_profile.location_strategy added successfully';
  END IF;
  
  -- Check business_programme_profiles columns
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'business_programme_profiles' 
    AND column_name IN ('meal_periods', 'day_pattern', 'menu_results_v2_id')
  ) THEN
    RAISE NOTICE '✅ business_programme_profiles columns added successfully';
  END IF;
END $$;

-- ========================================
-- NOTES
-- ========================================
-- After running this script:
-- 1. Test brand profile generation at /dashboard/brand
-- 2. Check for any console errors
-- 3. Verify location_strategy is being saved
-- 4. Monitor Edge Function logs for schema errors
