#!/usr/bin/env -S deno run --allow-net --allow-read --allow-env
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const envContent = await Deno.readTextFile('.env')
const envVars = {}
envContent.split('\n').forEach(line => {
  const match = line.match(/^([^=]+)=(.+)$/)
  if (match) {
    envVars[match[1]] = match[2].replace(/^["']|["']$/g, '')
  }
})

const supabase = createClient(
  'https://kvqdkohdpvmdylqgujpn.supabase.co',
  envVars.SUPABASE_SERVICE_ROLE_KEY
)

const businessId = 'f4679fa9-3120-4a59-9506-d059b010c34a'

console.log('🔍 Checking brand profile architecture...\n')

const { data, error } = await supabase
  .from('business_brand_profile')
  .select(`
    business_id,
    updated_at,
    brand_profile_v5_generated_at,
    trigger_updated_at,
    trigger_updated_by,
    commercial_baseline_mode,
    trigger_configuration
  `)
  .eq('business_id', businessId)
  .single()

if (error) {
  console.error('❌ Error:', error)
  Deno.exit(1)
}

console.log('📊 Current State:')
console.log('─'.repeat(60))
console.log(`Profile updated_at:      ${data.updated_at}`)
console.log(`V5 generated_at:         ${data.brand_profile_v5_generated_at}`)
console.log(`Trigger updated_at:      ${data.trigger_updated_at}`)
console.log(`Trigger updated_by:      ${data.trigger_updated_by}`)
console.log(`Commercial baseline:     ${data.commercial_baseline_mode}`)
console.log(`Trigger config exists:   ${data.trigger_configuration ? 'YES' : 'NO'}`)

console.log('\n🏗️  Architecture Analysis:')
console.log('─'.repeat(60))

if (data.brand_profile_v5_generated_at) {
  const v5Timestamp = new Date(data.brand_profile_v5_generated_at)
  const v5Age = Math.floor((new Date() - v5Timestamp) / 1000 / 60)
  console.log(`✅ V5 Profile: GENERATED ${v5Age} minutes ago`)
  console.log(`   → Created by: brand-profile-generator-v5`)
  console.log(`   → Generates: voice, guardrails, persona, segments`)
  console.log(`   → Saves to: brand_profile_v5 (JSONB)`)
} else {
  console.log(`❌ V5 Profile: NOT GENERATED`)
}

console.log('')

if (data.trigger_configuration) {
  const triggerTimestamp = new Date(data.trigger_updated_at)
  const triggerAge = Math.floor((new Date() - triggerTimestamp) / 1000 / 60 / 60 / 24)
  console.log(`✅ Trigger Config: GENERATED ${triggerAge} days ago`)
  console.log(`   → Created by: ${data.trigger_updated_by}`)
  console.log(`   → Generates: trigger rules for commercial strategy`)
  console.log(`   → Saves to: trigger_configuration, commercial_baseline_mode`)
} else {
  console.log(`❌ Trigger Config: NOT GENERATED`)
}

console.log('\n📌 KEY FINDING:')
console.log('═'.repeat(60))

if (data.brand_profile_v5_generated_at && data.trigger_updated_at) {
  const v5Time = new Date(data.brand_profile_v5_generated_at)
  const triggerTime = new Date(data.trigger_updated_at)
  const updatedTime = new Date(data.updated_at)
  
  const timeDiffHours = Math.abs(v5Time - triggerTime) / 1000 / 60 / 60
  
  console.log(`V5 Profile:      ${v5Time.toISOString()}`)
  console.log(`Trigger Config:  ${triggerTime.toISOString()}`)
  console.log(`Row Updated:     ${updatedTime.toISOString()}`)
  console.log('')
  console.log(`Time difference: ${Math.floor(timeDiffHours)} hours`)
  console.log('')
  
  if (timeDiffHours > 24) {
    console.log(`✅ CONCLUSION: These are generated by DIFFERENT functions`)
    console.log(`   • V5 updates brand_profile_v5 (voice, persona, etc.)`)
    console.log(`   • Some OTHER process updates trigger_configuration`)
  } else {
    console.log(`⚠️  Both updated recently - need to check which function`)
  }
}

console.log('\n🎯 Answer to your question:')
console.log('─'.repeat(60))
console.log('Q: Is brand-profile-generator-v5 the ONLY profile generator?')
console.log('A: V5 generates BRAND PROFILE (voice, persona, segments)')
console.log('   But trigger_configuration appears to be SEPARATE')
console.log('')
console.log('   Need to find: Where does trigger_configuration come from?')
