-- ============================================================================
-- ADD SIGNATURE_THEMES COLUMN TO BUSINESS_BRAND_PROFILE
-- ============================================================================
-- Array of extracted signature themes (e.g., "Dansk tradition", "Bar-program")
-- Enables easy filtering and querying by theme
--
-- Run this in Supabase SQL Editor:
-- https://supabase.com/dashboard/project/kvqdkohdpvmdylqgujpn/sql/new
-- ============================================================================

-- Add column (TEXT array for PostgreSQL native array support)
ALTER TABLE business_brand_profile 
ADD COLUMN IF NOT EXISTS signature_themes TEXT[];

-- Add comment
COMMENT ON COLUMN business_brand_profile.signature_themes IS 
  'Array of extracted signature themes from menu analysis (e.g., ["Dansk tradition", "Bar-program", "All-day dining"]). Generated by menu-overview-summary Edge Function.';

-- Create GIN index for array queries (enables fast "contains" searches)
CREATE INDEX IF NOT EXISTS idx_brand_profile_signature_themes 
ON business_brand_profile USING GIN (signature_themes);

-- Verify
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'business_brand_profile' 
  AND column_name = 'signature_themes';
