-- ============================================================================
-- ADD GASTRONOMIC_PROFILE COLUMN TO BUSINESS_BRAND_PROFILE
-- ============================================================================
-- Ultra-short 1-2 sentence factual profile of gastronomic identity
-- (price level + style, e.g., "Mellemklasse casual dining med fokus på...")
--
-- Run this in Supabase SQL Editor:
-- https://supabase.com/dashboard/project/kvqdkohdpvmdylqgujpn/sql/new
-- ============================================================================

-- Add column
ALTER TABLE business_brand_profile 
ADD COLUMN IF NOT EXISTS gastronomic_profile TEXT;

-- Add comment
COMMENT ON COLUMN business_brand_profile.gastronomic_profile IS 
  'Ultra-short 1-2 sentence gastronomic identity profile (price level + style). Generated by menu-overview-summary Edge Function.';

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_brand_profile_gastronomic_profile 
ON business_brand_profile (business_id) 
WHERE gastronomic_profile IS NOT NULL;

-- Verify
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'business_brand_profile' 
  AND column_name = 'gastronomic_profile';
