-- ============================================================================
-- ADD MENU_OVERVIEW_SUMMARY COLUMN TO BUSINESS_BRAND_PROFILE
-- ============================================================================
-- This column stores the cross-menu summary generated by menu-overview-summary
-- Edge Function, separate from brand_profile_v5 column
-- ============================================================================

-- Add menu_overview_summary column (JSONB, nullable)
ALTER TABLE business_brand_profile 
ADD COLUMN IF NOT EXISTS menu_overview_summary JSONB;

-- Add comment for documentation
COMMENT ON COLUMN business_brand_profile.menu_overview_summary IS 
'Cross-menu summary generated by menu-overview-summary Edge Function. Contains: cross_menu_summary (text), total_items (int), total_menus (int), overall_avg_price (int), menu_breakdown (array), signature_themes (array), generated_at (timestamp)';

-- Create index for faster queries on businesses with menu summaries
CREATE INDEX IF NOT EXISTS idx_business_brand_profile_has_menu_overview 
ON business_brand_profile ((menu_overview_summary IS NOT NULL));

-- Example query to check businesses with menu overview summaries
-- SELECT business_id, menu_overview_summary->>'cross_menu_summary' as summary
-- FROM business_brand_profile
-- WHERE menu_overview_summary IS NOT NULL;
