-- RUN THIS IN SUPABASE SQL EDITOR
-- https://supabase.com/dashboard/project/kvqdkohdpvmdylqgujpn/sql/new

-- Add missing Layer 3 fields to business_brand_profile
-- These fields are generated by V5 identity-profile.ts (Layer 3)

ALTER TABLE business_brand_profile 
ADD COLUMN IF NOT EXISTS core_values JSONB,
ADD COLUMN IF NOT EXISTS what_makes_us_different TEXT,
ADD COLUMN IF NOT EXISTS identity_confidence DECIMAL(3,2),
ADD COLUMN IF NOT EXISTS identity_reasoning TEXT;

-- Add comments to document what these columns are for
COMMENT ON COLUMN business_brand_profile.core_values IS 'Layer 3: AI-generated core values array (e.g. ["Kvalitet", "Nærhed"])';
COMMENT ON COLUMN business_brand_profile.what_makes_us_different IS 'Layer 3: AI-generated differentiation statement';
COMMENT ON COLUMN business_brand_profile.identity_confidence IS 'Layer 3: AI confidence score 0.00-1.00 for identity generation';
COMMENT ON COLUMN business_brand_profile.identity_reasoning IS 'Layer 3: AI reasoning/explanation for identity decisions';

-- Verify columns were added
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'business_brand_profile' 
AND column_name IN ('core_values', 'what_makes_us_different', 'identity_confidence', 'identity_reasoning')
ORDER BY column_name;
