import { useState } from 'react';
import { useTranslation } from 'react-i18next';

import { BrandProfileSection } from './BrandProfileSection';
import { BrandSectionIcon } from './BrandSectionIcon';
// import { VoiceArchetypeSelector } from './VoiceArchetypeSelector'; // REMOVED Sprint 1
import PostLengthGuidelines from './PostLengthGuidelines';
import { ProgrammeRevenueWeights } from './ProgrammeRevenueWeights';
import { RevenueDriversDisplay } from './RevenueDriversDisplay';
import { CommercialStrategySection } from './CommercialStrategySection';

interface ToneModel {
  primary_keywords?: string[];
  writing_rules?: string[];
  good_examples?: string[];
  avoid_examples?: string[];
  formality?: string;
  confidence?: string;
}

interface ContentPillar {
  hook: string;
  usage?: string;
}

interface ContentStrategy {
  primary_goal: 'drive_footfall' | 'build_brand';
  goal_blend: { drive_footfall: number; build_brand: number };
  footfall_signals: string[];
  brand_anchors: string[];
  content_category_weights: { product_menu: number; craving_visual: number; behind_scenes: number; team_people: number };
  anchors?: string[]; // Natural moments (Slot B/C content anchors)
}

interface LocationContext {
  type: string;
  score: number;
  seasonal: boolean;
  audiences: string[];
}

interface TimeSlot {
  programmes: string[];
  audiences: string[];
  contextual_drivers?: string[];
  contexts?: string[];
}

interface AudienceFramework {
  primaryAudiences: string[];
  locationContexts: LocationContext[];
  timeSlots: TimeSlot[];
  seasonalVariation?: {
    summerAudiences?: string[];
    winterAudiences?: string[];
  } | null;
  complexity: 'simple' | 'moderate' | 'complex';
}

interface VoiceSystem {
  primaryArchetype: string;
  programmeSpecific?: Record<string, any>;
  complexity: string;
}

interface BrandProfile {
  // Gruppe 1 — Identitet
  brand_essence: string;
  brand_essence_elaboration?: string | null;
  identity_keywords?: string[] | null;
  // Layer 3 fields
  positioning?: string | null;
  values?: string[] | null;
  what_makes_us_different?: string | null;
  // Gruppe 2 — Stemme
  tone_of_voice_value?: string;
  tone_model?: ToneModel | null;
  typical_openings?: string[];
  humor_level?: string;
  menu_description_examples?: string[] | null;  // V5.2: Examples teaching menu description style
  // Legacy tone (old profiles)
  tone_of_voice?: { primary_tone: string; attributes: string[]; formality_level: string } | null;
  // Gruppe 3 — Content Pillars
  content_hooks: ContentPillar[];
  // Gruppe 4 — Grænser
  voice_constraints?: string | null;
  emotional_promise?: string | null;
  content_exclusions?: string | null;
  signature_phrases?: string[];
  // Gruppe 5 — Baggrundskontekst
  target_audience?: { primary: string; characteristics: string[] };
  brand_origin_story?: string;
  // Business type — AI-inferred free text (hybrid-friendly)
  business_character?: string | null;
  // Business archetype — validated enum classification
  business_archetype?: string | null;
  // Voice derivation rationale (shown collapsed in Stemme section)
  voice_rationale?: string | null;
  // REMOVED (Sprint 1): voice_options, voice_archetype
  // Owner gets ONE voice (opinionated). Switching between archetypes removed.
  // Owner document — human-readable brand summary (generated by Stage B4)
  owner_document?: {
    brand_feel?: string | null;
    tone_sentence?: string | null;
    usps?: string[];
    audience?: { occasions?: string[] | null; primary?: string | null; secondary?: string | null; tertiary?: string | null } | null;
    caption_examples?: string[];
  } | null;
  // Stage B5 — structured audience segments
  audience_segments?: {
    business_model_type?: string | null;  // B5: "offer_led" | "occasion_led" | "destination_led" | "audience_led"
    primary_copy_hook?: string | null;    // B5: "product" | "location" | "programme" | "identity"
    audience_breadth?: string | null;     // B5: "narrow" | "mixed" | "broad"
    segments_rationale?: string | null;   // B5: why this many segments for this business
    primary_mindset?: string | null;
    primary_segment_id?: string | null;
    content_rotation_note?: string | null;
    tourist_factor?: 'none' | 'minor' | 'moderate' | 'dominant' | null;
    deduced_from?: string[];
    segments: Array<{
      id?: string;
      label: string;
      name: string;
      priority: 'primary' | 'secondary' | 'niche';
      strategic_value?: 'high' | 'medium' | 'low';
      strategic_value_rationale?: string;
      mindset_description?: string;
      who?: string;
      timing: Array<{ day: string; hour_start: number; hour_end: number }>;
      visit_pattern?: { service_period: string; decision_type: string };
      motivation: string;
      primary_motivation?: string;
      content_angles: Array<{ label: string; cta_type: string; post_timing: string; tone_note?: string }>;
      loyalty_weight?: 'high' | 'medium' | 'low';
    }>;
  } | null;
  // Legacy / internal (not displayed)
  brand_positioning?: string;
  banned_words?: string[];
  never_say?: string[];
  voice_confidence_score?: number;
  content_strategy?: ContentStrategy | null;
  // New multi-dimensional frameworks (2026)
  audience_framework?: AudienceFramework | null;
  voice_system?: VoiceSystem | null;
  // Post length guidelines by content type
  post_length_guidelines?: Array<{
    content_type: string;
    sentences: string;
    characters: string;
    structure: string;
    rationale: string;
  }> | null;
  // Task 4.1: Programme revenue weights for rotation priority
  programme_revenue_weights?: Record<string, number> | null;
  // Commercial strategy fields
  commercial_baseline_mode?: 'booking_push' | 'footfall_push' | 'balanced';
  trigger_configuration?: any;
  commercial_strategy_reasoning?: string;
  trigger_updated_by?: 'ai' | 'manual' | null;
}

interface BrandProfileDisplayProps {
  profile: BrandProfile;
  businessId?: string;
  onRegenerate?: () => void;
  onArchetypeChanged?: (archetype: string) => void;
}

export function BrandProfileDisplay({ profile, businessId, onRegenerate, onArchetypeChanged }: BrandProfileDisplayProps) {
  const { t } = useTranslation();
  const [gruppe1Open, setGruppe1Open] = useState(false);

  const toneChips = profile.tone_model?.primary_keywords?.filter(Boolean) ?? [];
  const contentPillars = Array.isArray(profile.content_hooks) ? profile.content_hooks : [];
  const avoidExamples = profile.tone_model?.avoid_examples?.filter(Boolean) ?? [];
  const signaturePhrases = (profile.signature_phrases ?? []).slice(0, 5);
  const firstOpening = profile.typical_openings?.[0] ?? null;

  // Helper to format archetype name
  const formatArchetypeName = (archetype: string): string => {
    const names: Record<string, string> = {
      fine_dining: 'Fine Dining',
      casual_dining: 'Casual Dining',
      cafe_bistro: 'Café Bistro',
      cafe_bar: 'Café/Bar (hybrid)',
      restaurant_bar: 'Restaurant/Bar',
      wine_bar: 'Vinbar',
      coffee_shop: 'Kaffebar',
      quick_service: 'Quick Service',
      bakery: 'Bageri',
      morning_cafe: 'Morgencafé',
      brunch_cafe: 'Brunchcafé',
      all_day_cafe: 'Heldagscafé',
      lunch_restaurant: 'Frokostrestaurant',
      dinner_restaurant: 'Aftenrestaurant',
      full_service_restaurant: 'Restaurant (fuld service)',
      evening_bar: 'Aftenbar',
      late_night_bar: 'Natbar',
      nightlife_bar: 'Natteliv',
      brunch_specialist: 'Brunchspecialist',
      fast_casual: 'Fast Casual'
    };
    return names[archetype] || archetype.replace(/_/g, ' ');
  };

  // Helper to get archetype icon emoji
  const getArchetypeIcon = (archetype: string): string => {
    const icons: Record<string, string> = {
      fine_dining: '⭐',
      casual_dining: '🍽️',
      cafe_bistro: '☕',
      cafe_bar: '🍷',
      restaurant_bar: '🍽️🍸',
      wine_bar: '🍷',
      coffee_shop: '☕',
      quick_service: '🚀',
      bakery: '🥐',
      morning_cafe: '🌅',
      brunch_cafe: '🥞',
      all_day_cafe: '☕',
      lunch_restaurant: '🍴',
      dinner_restaurant: '🌙',
      full_service_restaurant: '🍽️',
      evening_bar: '🍸',
      late_night_bar: '🌃',
      nightlife_bar: '🎉',
      brunch_specialist: '🥞',
      fast_casual: '🍔'
    };
    return icons[archetype] || '🏪';
  };

  // Normalise audience_segments: handle both old flat-array and new object format
  const normalisedAudienceSegments = (() => {
    const raw = profile.audience_segments;
    if (!raw) return null;
    if (Array.isArray(raw)) return raw.length > 0 ? { segments: raw } : null;
    // Include object if it has segments OR classification fields (broad businesses may have 0 segments)
    const hasClassification = typeof (raw as any).business_model_type === 'string';
    const segs = Array.isArray((raw as any).segments) ? (raw as any).segments : [];
    if (segs.length > 0 || hasClassification) return { ...raw, segments: segs } as typeof raw & { segments: NonNullable<typeof raw>['segments'] };
    return null;
  })();
  const humorLabel = profile.humor_level
    ? (t(`brand.display.humor.${profile.humor_level}`, { defaultValue: profile.humor_level }))
    : null;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-end">
        {onRegenerate && (
          <button
            onClick={onRegenerate}
            className="px-4 py-2 text-sm font-medium text-cta hover:text-cta-text hover:bg-cta-surface rounded-lg transition-colors"
          >
          🔄 {t('brand.display.regenerate')}
          </button>
        )}
      </div>

      {/* ── DIN BRANDPROFIL (owner document) ─────────────────────── */}
      {profile.owner_document && (
        <div className="bg-surface rounded-xl border border-border p-6 space-y-5">
          <p className="text-xs font-semibold tracking-widest text-info uppercase">Din brandprofil</p>

          {/* Brand essence — pull-quote (primary: brand_essence from DB, fallback: brand_feel from owner_document) */}
          {(profile.brand_essence || profile.owner_document.brand_feel) && (
            <p className="text-lg font-semibold text-text leading-snug border-l-4 border-cta pl-4">
              {profile.brand_essence || profile.owner_document.brand_feel}
            </p>
          )}

          {/* Tone sentence */}
          {profile.owner_document.tone_sentence && (
            <div>
              <p className="text-xs font-semibold text-info uppercase tracking-wide mb-1">Stemme</p>
              <p className="text-sm text-text">{profile.owner_document.tone_sentence}</p>
            </div>
          )}

          {/* USPs */}
          {profile.owner_document.usps && profile.owner_document.usps.length > 0 && (
            <div>
              <p className="text-xs font-semibold text-info uppercase tracking-wide mb-2">Hvad I tilbyder</p>
              <ul className="space-y-1">
                {profile.owner_document.usps.map((usp, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-text">
                    <span className="text-success mt-0.5">•</span>
                    <span>{usp}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Audience — Stage B5 segment cards (preferred) or B4 occasions (fallback) */}
          {normalisedAudienceSegments ? (
            <div>
              {/* DEPRECATED: Stage B5 Business-Level Segments Warning */}
              <div className="mb-4 bg-yellow-50 border-l-4 border-yellow-500 p-3 rounded">
                <p className="text-xs font-bold uppercase text-yellow-900 mb-1">
                  ⚠️ DEPRECATED: Business-Level Segments (Stage B5)
                </p>
                <p className="text-sm text-gray-700 mb-2">
                  These segments are business-level averages across all programmes. 
                  For precise, programme-specific segments with evidence, see <strong>Programme Profiles (Layers 1-4)</strong> below.
                </p>
                <p className="text-xs text-gray-600">
                  Layer 4 replaces this with programme-aware audience segmentation that adapts to different service periods.
                </p>
              </div>

              <p className="text-xs font-semibold text-info uppercase tracking-wide mb-2">Jeres gæster</p>
              {(normalisedAudienceSegments as any).primary_mindset && (
                <p className="text-sm text-text italic mb-3 border-l-2 border-cta pl-3">
                  {(normalisedAudienceSegments as any).primary_mindset}
                </p>
              )}

              <div className="space-y-2">
                {normalisedAudienceSegments.segments.map((seg: any, i: number) => (
                  <div key={i} className="rounded-lg border border-border p-3 space-y-1.5">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="text-sm font-semibold text-text">{seg.people_type ?? seg.label ?? seg.name}</span>
                      <span className={`text-xs px-2 py-0.5 rounded-full ${
                        seg.priority === 'primary' ? 'bg-cta-surface text-cta' :
                        seg.priority === 'secondary' ? 'bg-accent-surface text-info' :
                        'bg-surface text-info border border-border'
                      }`}>
                        {seg.priority === 'primary' ? 'Primær' : seg.priority === 'secondary' ? 'Sekundær' : 'Niche'}
                      </span>
                    </div>
                    {/* Timing — compact day/hour summary */}
                    {seg.timing && seg.timing.length > 0 && (() => {
                      const dayShort: Record<string, string> = { monday: 'Man', tuesday: 'Tir', wednesday: 'Ons', thursday: 'Tor', friday: 'Fre', saturday: 'Lør', sunday: 'Søn', weekday: 'Hverdage', weekend: 'Weekend' };
                      return (
                        <p className="text-xs text-info">
                          {seg.timing.map((t: { day: string; hour_start: number; hour_end: number }) => `${dayShort[t.day] ?? t.day} ${t.hour_start}–${t.hour_end}`).join(' · ')}
                        </p>
                      );
                    })()}
                    {(seg.mindset_description || seg.who) && (
                      <p className="text-sm text-text">{seg.mindset_description ?? seg.who}</p>
                    )}
                    {seg.motivation && <p className="text-xs text-info italic">{seg.motivation}</p>}
                  </div>
                ))}
              </div>

            </div>
          ) : profile.owner_document.audience ? (
            <div>
              <p className="text-xs font-semibold text-info uppercase tracking-wide mb-2">Jeres gæster</p>
              <div className="space-y-1">
                {profile.owner_document.audience.occasions && profile.owner_document.audience.occasions.length > 0
                  ? profile.owner_document.audience.occasions.map((occasion, i) => (
                      <p key={i} className="text-sm text-text">{occasion}</p>
                    ))
                  : (<>
                      {profile.owner_document.audience.primary && (
                        <p className="text-sm text-text">{profile.owner_document.audience.primary}</p>
                      )}
                      {profile.owner_document.audience.secondary && (
                        <p className="text-sm text-text">{profile.owner_document.audience.secondary}</p>
                      )}
                      {profile.owner_document.audience.tertiary && (
                        <p className="text-sm text-text">{profile.owner_document.audience.tertiary}</p>
                      )}
                    </>)
                }
              </div>
            </div>
          ) : null}


        </div>
      )}

      {/* ── GRUPPE 1 — IDENTITET ─────────────────────────────── */}
      <div className="bg-accent-surface rounded-xl p-8 border border-accent space-y-5">
        <div>
          <p className="text-xs font-semibold tracking-widest text-info uppercase mb-2">
          {t('brand.display.group1Badge')}
          </p>
          <p className="text-lg font-bold text-text leading-snug">
            {profile.brand_essence}
          </p>
        </div>

        {/* Business Archetype — validated classification */}
        {profile.business_archetype && (
          <div className="flex items-start gap-3 pt-1">
            <span className="text-xl shrink-0 mt-0.5">{getArchetypeIcon(profile.business_archetype)}</span>
            <div>
              <p className="text-xs font-semibold text-info uppercase tracking-wide mb-1">Forretningstype (klassificeret)</p>
              <p className="text-sm font-medium text-text leading-relaxed">{formatArchetypeName(profile.business_archetype)}</p>
            </div>
          </div>
        )}

        {/* Layer 3: Positioning */}
        {profile.positioning && (
          <div className="flex items-start gap-3 pt-1">
            <BrandSectionIcon id="positioning" className="w-5 h-5 text-text shrink-0 mt-0.5" />
            <div>
              <p className="text-xs font-semibold text-info uppercase tracking-wide mb-1">Positioning (Layer 3)</p>
              <p className="text-sm font-medium text-text leading-relaxed">{profile.positioning}</p>
            </div>
          </div>
        )}

        {/* Layer 3: Core Values */}
        {profile.values && profile.values.length > 0 && (
          <div className="flex items-start gap-3 pt-1">
            <BrandSectionIcon id="values" className="w-5 h-5 text-text shrink-0 mt-0.5" />
            <div>
              <p className="text-xs font-semibold text-info uppercase tracking-wide mb-1">Core Values (Layer 3)</p>
              <ul className="space-y-1">
                {profile.values.map((value, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-text">
                    <span className="text-success mt-0.5">•</span>
                    <span>{value}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {/* Layer 3: What Makes Us Different */}
        {profile.what_makes_us_different && (
          <div className="flex items-start gap-3 pt-1">
            <BrandSectionIcon id="unique" className="w-5 h-5 text-text shrink-0 mt-0.5" />
            <div>
              <p className="text-xs font-semibold text-info uppercase tracking-wide mb-1">What Makes Us Different (Layer 3)</p>
              <p className="text-sm font-medium text-text leading-relaxed">{profile.what_makes_us_different}</p>
            </div>
          </div>
        )}

        {profile.brand_essence_elaboration && (
          <div>
            <button
              onClick={() => setGruppe1Open(o => !o)}
              className="flex items-center gap-1.5 text-xs font-medium text-cta hover:text-cta-text transition-colors mt-1"
            >
              <span>{gruppe1Open ? '▾' : '▸'}</span>
              <span>{gruppe1Open ? t('brand.display.hideDetails') : t('brand.display.showPositioning')}</span>
            </button>

            {gruppe1Open && (
              <div className="mt-4 space-y-4">
                {/* Rich audience framework (preferred) */}
                {profile.audience_framework ? (
                  <div className="space-y-4">
                    {/* Primary audiences */}
                    {profile.audience_framework.primaryAudiences && profile.audience_framework.primaryAudiences.length > 0 && (
                      <div>
                        <p className="text-xs font-semibold text-info uppercase tracking-wide mb-2">Gæstegrundlag</p>
                        <div className="flex flex-wrap gap-2">
                          {profile.audience_framework.primaryAudiences.map((aud, i) => (
                            <span key={i} className="px-3 py-1 bg-cta-surface text-cta text-sm rounded-full border border-cta">
                              {aud}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Time slots with integrated location context */}
                    {profile.audience_framework.timeSlots && profile.audience_framework.timeSlots.length > 0 && (
                      <div>
                        <p className="text-xs font-semibold text-info uppercase tracking-wide mb-2">Variation over dagen</p>
                        <div className="grid grid-cols-2 gap-2">
                          {profile.audience_framework.timeSlots.map((slot, i) => {
                            const programmes = Array.isArray(slot.programmes) ? slot.programmes.join(', ') : ''
                            
                            // Derive display label and icon from programme names
                            const getProgrammeDisplay = (progs: string) => {
                              const p = progs.toLowerCase()
                              if (/brunch|morgenmad|breakfast|morgenkaffe/.test(p)) return { icon: '🌅', label: 'Brunch/Morgen' }
                              if (/frokost|lunch/.test(p)) return { icon: '🍽️', label: 'Frokost' }
                              if (/kaffe|kage|cake|eftermiddag/.test(p)) return { icon: '☕', label: 'Eftermiddag' }
                              if (/aften|middag|dinner/.test(p)) return { icon: '🌆', label: 'Aften' }
                              if (/cocktail|bar|drink|nat/.test(p)) return { icon: '🌙', label: 'Cocktails/Nat' }
                              return { icon: '⏰', label: progs }
                            }
                            
                            const display = getProgrammeDisplay(programmes)
                            
                            // Match location contexts to this time slot based on audience overlap
                            const locationContexts = profile.audience_framework?.locationContexts || []
                            const contextLabels: Record<string, string> = {
                              waterfront_tourist: 'Vandkant',
                              downtown_business: 'Bymidten',
                              residential_local: 'Lokalt',
                              nightlife_district: 'Natteliv',
                              shopping_district: 'Shopping',
                              waterfront: 'Vandkant',
                              city_centre: 'Centrum'
                            }
                            
                            const relevantContexts = locationContexts
                              .filter(ctx => {
                                // Check if any of the slot's audiences overlap with context audiences
                                return slot.audiences.some(aud => ctx.audiences.includes(aud))
                              })
                              .map(ctx => contextLabels[ctx.type] || ctx.type)
                            
                            return (
                              <div key={i} className="p-3 bg-surface rounded border border-border">
                                <div className="flex items-center gap-2 mb-1.5">
                                  <span className="text-base">{display.icon}</span>
                                  <div className="flex-1">
                                    <p className="text-xs font-semibold text-text">{display.label}</p>
                                  </div>
                                </div>
                                {programmes && (
                                  <p className="text-xs font-medium text-text mb-1">{programmes}</p>
                                )}
                                {relevantContexts.length > 0 && (
                                  <p className="text-[10px] text-info mb-1.5">
                                    📍 {relevantContexts.join(' + ')}
                                  </p>
                                )}
                                <p className="text-xs text-text-secondary leading-relaxed">
                                  {slot.audiences.join(', ')}
                                </p>
                              </div>
                            )
                          })}
                        </div>
                      </div>
                    )}
                  </div>
                ) : profile.brand_essence_elaboration ? (
                  /* Fallback: old compressed text */
                  <p className="text-base text-text-secondary leading-relaxed border-l-4 border-info pl-4">
                    {profile.brand_essence_elaboration}
                  </p>
                ) : null}

                {/* Task 4.1: Programme Revenue Weights (multi-programme venues only) */}
                {profile.audience_framework?.timeSlots && businessId && (() => {
                  const programmes = profile.audience_framework.timeSlots
                    .flatMap(slot => slot.programmes || [])
                    .filter((p, i, arr) => arr.indexOf(p) === i); // Deduplicate
                  
                  if (programmes.length >= 2) {
                    return (
                      <div className="mt-6 pt-6 border-t border-border">
                        <ProgrammeRevenueWeights
                          businessId={businessId}
                          programmes={programmes}
                          initialWeights={profile.programme_revenue_weights}
                          onWeightsChanged={() => {
                            if (onArchetypeChanged) {
                              onArchetypeChanged('');
                            }
                          }}
                        />
                      </div>
                    );
                  }
                  return null;
                })()}

                {/* Revenue Drivers (multi-primary temporal analysis) */}
                {businessId && (
                  <div className="mt-6 pt-6 border-t border-border">
                    <RevenueDriversDisplay businessId={businessId} />
                  </div>
                )}

              </div>
            )}
          </div>
        )}
      </div>

      {/* ── GRUPPE 2 — STEMME ───────────────────────────────── */}
      <BrandProfileSection
        title={t('brand.display.voice.title')}
        icon={<BrandSectionIcon id="voice" className="w-6 h-6 text-text" />}
        badge={t('brand.display.voice.badge')}
      >
        {/* ── SPRINT 1: Voice archetype selector REMOVED (Complexity Reduction) ── */}
        {/* Owner gets ONE voice (opinionated). Switching between archetypes removed. */}
        
        {/* Tone keyword chips */}
        {toneChips.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-4">
                {toneChips.map((kw, i) => (
                  <span key={i} className="px-3 py-1 bg-accent-surface text-accent-text text-xs font-medium rounded-full border border-accent">
                    {kw}
                  </span>
                ))}
              </div>
            )}

            {/* Rules text */}
            {profile.tone_of_voice_value ? (
              <div className="bg-surface-alt rounded-lg p-4 border border-border mb-4">
                <pre className="text-sm text-text whitespace-pre-wrap font-sans leading-relaxed">
                  {(profile.tone_of_voice_value || '').replace(/\s*\(signal:[^)]+\)/g, '')}
                </pre>
              </div>
            ) : profile.tone_of_voice?.primary_tone ? (
              <div className="space-y-3 mb-4">
                <div>
                  <span className="text-sm font-medium text-text-muted">Primær tone:</span>
                  <p className="text-base font-medium text-text">{profile.tone_of_voice.primary_tone}</p>
                </div>
                <p className="text-xs text-warning bg-warning-surface px-3 py-2 rounded">
                  {t('brand.display.voice.legacyWarning')}
                </p>
              </div>
            ) : null}

            {/* Voice rationale */}
            {profile.voice_rationale && (
              <details className="mt-4 group">
                <summary className="cursor-pointer text-xs font-medium text-text-muted hover:text-text-secondary list-none flex items-center gap-1">
                  <span className="group-open:rotate-90 transition-transform inline-block">▶</span>
                  {t('brand.display.voice.rationale')}
                </summary>
                <div className="mt-2 p-3 bg-surface-alt rounded-lg border border-border">
                  <p className="text-sm text-text-secondary leading-relaxed">{profile.voice_rationale}</p>
                </div>
              </details>
            )}

            {/* Menu description examples (V5.2) */}
            {profile.menu_description_examples && profile.menu_description_examples.length > 0 && (
              <div className="mt-4 bg-surface-alt rounded-lg p-4 border border-border">
                <p className="text-xs font-semibold text-text-muted uppercase tracking-wide mb-3">
                  🍽️ Menueksempler (sådan beskriver vi mad)
                </p>
                <div className="space-y-3">
                  {profile.menu_description_examples.map((example, i) => (
                    <div key={i} className="p-3 bg-surface rounded border border-border-subtle">
                      <p className="text-sm text-text leading-relaxed italic">"{example}"</p>
                    </div>
                  ))}
                </div>
                <p className="text-xs text-text-muted mt-3">
                  Disse eksempler viser hvordan vi beskriver retter med den rigtige balance mellem casual tone og kulinarisk bevidsthed.
                </p>
              </div>
            )}

            {/* Typical opening + humor */}
            {(firstOpening || humorLabel) && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-4">
                {firstOpening && (
                  <div className="p-3 bg-success-surface rounded-lg border border-success">
                    <p className="text-xs font-medium text-success mb-1">{t('brand.display.voice.typicalOpening')}</p>
                    <p className="text-sm text-text italic">"{firstOpening}"</p>
                  </div>
                )}
                {humorLabel && (
                  <div className="p-3 bg-warning-surface rounded-lg border border-warning">
                    <p className="text-xs font-medium text-warning-text mb-1">{t('brand.display.voice.humorLabel')}</p>
                    <p className="text-sm text-text">{humorLabel}</p>
                  </div>
                )}
              </div>
            )}


        {/* ── POST LENGTH GUIDELINES ──────────────────────────── */}
        {businessId && (
          <div className="mt-6 pt-6 border-t border-border">
            <PostLengthGuidelines
              guidelines={profile.post_length_guidelines || []}
              businessId={businessId}
              onUpdate={async (guidelines) => {
                try {
                  // TODO: post_length_guidelines field doesn't exist in current schema
                  // Consider adding to brand_profile_v5 JSON or creating new column
                  console.log('Post length guidelines update skipped (field not in schema):', guidelines);
                  /* const { error } = await supabase
                    .from('business_brand_profile')
                    .update({ post_length_guidelines: guidelines })
                    .eq('business_id', businessId);
                  
                  if (error) {
                    console.error('Failed to save post length guidelines:', error);
                    throw error;
                  } */
                  
                  console.log('✅ Post length guidelines saved successfully');
                } catch (error) {
                  console.error('Error saving post length guidelines:', error);
                  throw error;
                }
              }}
              editable={true}
            />
          </div>
        )}
      </BrandProfileSection>

      {/* ── GRUPPE 3 — CONTENT PILLARS ─────────────────────── */}
      <BrandProfileSection
        title={t('brand.display.pillars.title')}
        icon={<BrandSectionIcon id="pillars" className="w-6 h-6 text-text" />}
        badge={t('brand.display.pillars.badge')}
      >
        <div className="space-y-3">
          {contentPillars.map((pillar, i) => (
            <div key={i} className="border-l-4 border-accent pl-4 py-1.5">
              <p className="font-medium text-text">→ {pillar.hook}</p>
              {pillar.usage && <p className="text-sm text-text-muted mt-0.5">{pillar.usage}</p>}
            </div>
          ))}
          {contentPillars.length === 0 && (
            <p className="text-sm text-text-muted italic">{t('brand.display.pillars.empty')}</p>
          )}
        </div>
      </BrandProfileSection>

      {/* ── GRUPPE 4 — GRÆNSER ──────────────────────────────── */}
      <BrandProfileSection
        title={t('brand.display.limits.title')}
        icon={<BrandSectionIcon id="limits" className="w-6 h-6 text-text" />}
        badge={t('brand.display.limits.badge')}
      >
        {/* Emotional promise */}
        {profile.emotional_promise && (
          <div className="p-4 bg-success-surface rounded-lg border border-success mb-4">
            <p className="text-xs font-semibold text-success uppercase tracking-wide mb-1">💡 Brandfølelse</p>
            <p className="text-sm text-text leading-relaxed">{profile.emotional_promise}</p>
          </div>
        )}

        {/* Content exclusions */}
        {profile.content_exclusions && (
          <div className="p-4 bg-error-surface rounded-lg border border-error mb-4">
            <p className="text-xs font-semibold text-error uppercase tracking-wide mb-1">🚫 Aldrig i opslag</p>
            <p className="text-xs text-error opacity-70 mb-2">Gælder ikke menu posts</p>
            <p className="text-sm text-text leading-relaxed">{profile.content_exclusions.replace(/\s*Undtagelse:\s*gælder ikke menu-opslag\.?/i, '').trim()}</p>
          </div>
        )}

        {/* Voice constraints */}
        {profile.voice_constraints && (
          <div className="p-4 bg-warning-surface rounded-lg border border-warning mb-4">
            <p className="text-xs font-semibold text-warning-text uppercase tracking-wide mb-1">{t('brand.display.limits.principle')}</p>
            <p className="text-sm text-text leading-relaxed">{profile.voice_constraints}</p>
          </div>
        )}

        {/* Avoid examples */}
        {avoidExamples.length > 0 && (
          <div className="mb-4">
            <p className="text-xs font-medium text-error mb-2">{t('brand.display.limits.avoid')}</p>
            <div className="space-y-2">
              {avoidExamples.map((ex, i) => (
                <div key={i} className="flex items-start gap-2 p-2 bg-error-surface rounded text-sm text-text-secondary">
                  <span className="text-error shrink-0 mt-0.5">✕</span>
                  <span>"{ex}"</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Signature phrases */}
        {signaturePhrases.length > 0 && (
          <div>
            <p className="text-xs font-medium text-accent-text mb-2">{t('brand.display.limits.signature')}</p>
            <div className="flex flex-wrap gap-2">
              {signaturePhrases.map((phrase, i) => (
                <span
                  key={i}
                  className="px-3 py-1.5 bg-cta-surface text-cta-text text-sm font-medium rounded-lg border border-cta cursor-pointer hover:bg-cta hover:text-text-inverse transition-colors"
                  onClick={() => navigator.clipboard?.writeText(phrase)}
                  title={t('brand.display.limits.copy')}
                >
                  "{phrase}"
                </span>
              ))}
            </div>
          </div>
        )}

        {(!profile.voice_constraints && avoidExamples.length === 0 && signaturePhrases.length === 0) && (
          <p className="text-sm text-text-muted italic">{t('brand.display.limits.empty')}</p>
        )}
      </BrandProfileSection>

      {/* ── POST STRATEGI ───────────────────────────────────── */}
      {profile.content_strategy && (() => {
        // Migrate legacy 3-goal structure to 2-goal framework
        const rawCs = profile.content_strategy!;
        const cs = { ...rawCs };
        
        // If legacy retain_loyalty exists, merge it into build_brand
        if (cs.goal_blend && 'retain_loyalty' in cs.goal_blend) {
          const legacy = cs.goal_blend as any;
          cs.goal_blend = {
            drive_footfall: legacy.drive_footfall || 0,
            build_brand: (legacy.build_brand || 0) + (legacy.retain_loyalty || 0)
          };
        }
        
        // TWO-DIMENSIONAL FRAMEWORK: Only drive_footfall and build_brand
        const GOAL_LABELS: Record<string, { label: string; color: string; bg: string; border: string }> = {
          drive_footfall: { label: t('brand.display.strategy.goals.drive_footfall'), color: 'text-success', bg: 'bg-success-surface', border: 'border-success' },
          build_brand:    { label: t('brand.display.strategy.goals.build_brand'),    color: 'text-info',  bg: 'bg-info-surface',  border: 'border-info' },
        };
        const primaryMeta = GOAL_LABELS[cs.primary_goal] ?? GOAL_LABELS.drive_footfall;
        const allSignals = [
          ...(cs.footfall_signals ?? []).map(s => ({ label: s, icon: '🏃', tip: t('brand.display.strategy.tips.footfall') })),
          ...(cs.brand_anchors ?? []).map(s => ({ label: s, icon: '⚓', tip: t('brand.display.strategy.tips.brand') })),
        ];

        // Build a prose rationale from the strategy signals using locale templates
        const buildRationale = (): string => {
          const goalLabels: Record<string, string> = {
            drive_footfall: t('brand.display.strategy.goals.drive_footfall'),
            build_brand:    t('brand.display.strategy.goals.build_brand'),
          };
          const blend = cs.goal_blend ?? {} as Record<string, number>;
          const sorted = (Object.entries(blend) as [string, number][]).sort((a, b) => b[1] - a[1]);
          const parts: string[] = [];

          sorted.forEach(([key, pct]) => {
            const label = goalLabels[key] ?? key;
            if (key === 'drive_footfall') {
              const sigs = cs.footfall_signals ?? [];
              if (sigs.length > 0) {
                parts.push(t('brand.display.strategy.rationale.footfall_with_signals', { label, pct, signals: sigs.join(', ') }));
              } else {
                parts.push(t('brand.display.strategy.rationale.footfall_no_signals', { label, pct }));
              }
            } else if (key === 'build_brand') {
              const anchors = cs.brand_anchors ?? [];
              if (anchors.length > 0) {
                parts.push(t('brand.display.strategy.rationale.brand_with_anchors', { label, pct, anchors: anchors.join(', ') }));
              } else {
                parts.push(t('brand.display.strategy.rationale.brand_no_anchors', { label, pct }));
              }
            }
          });

          return parts.join('\n\n');
        };

        const rationale = buildRationale();
        return (
          <BrandProfileSection
            title={t('brand.display.strategy.title')}
            icon={<BrandSectionIcon id="strategy" className="w-6 h-6 text-text" />}
            badge={t('brand.display.strategy.badge')}
          >
            {/* Primary goal badge */}
            <div className="mb-5">
              <p className="text-xs font-medium text-text-muted mb-2">{t('brand.display.strategy.primaryGoal')}</p>
              <span className={`inline-flex items-center gap-1.5 px-4 py-1.5 rounded-full text-sm font-semibold border ${primaryMeta.bg} ${primaryMeta.color} ${primaryMeta.border}`}>
                {cs.primary_goal === 'drive_footfall' ? '🏃' : '⚓'}
                {primaryMeta.label}
              </span>
            </div>

            {/* Goal blend bar — removed; percentages imply precision the model weights do not have. Direction is communicated via rationale prose below. */}

            {/* Content category weights — hidden from UI (used internally as slot-planner sort weights, not post-count allocations; showing percentages alongside goal_blend would mislead owners into reconciling two non-comparable distributions) */}

            {/* Rationale */}
            {rationale && (
              <div className="mt-2 p-4 bg-warning-surface border border-warning rounded-lg">
                <p className="text-xs font-semibold text-warning-text uppercase tracking-wide mb-3">
                  {t('brand.display.strategy.rationaleTitle')}
                </p>
                <div className="space-y-2">
                  {rationale.split('\n\n').map((para, i) => {
                    // Render **bold** text within each paragraph
                    const parts = para.split(/\*\*(.+?)\*\*/);
                    return (
                      <p key={i} className="text-sm text-text leading-relaxed">
                        {parts.map((part, j) =>
                          j % 2 === 1
                            ? <strong key={j} className="font-semibold text-text">{part}</strong>
                            : part
                        )}
                      </p>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Signals — compact chip row */}
            {allSignals.length > 0 && (
              <div>
                <p className="text-xs font-medium text-text-muted mb-2">{t('brand.display.strategy.signalsTitle')}</p>
                <div className="flex flex-wrap gap-2">
                  {allSignals.map((s, i) => (
                    <span key={i} className="flex items-center gap-1 px-3 py-1 bg-surface-alt border border-border text-xs text-text-secondary rounded-full" title={s.tip}>
                      <span>{s.icon}</span>{s.label}
                    </span>
                  ))}
                </div>
              </div>
            )}

          </BrandProfileSection>
        );
      })()}

      {/* ── COMMERCIAL STRATEGY ───────────────────────────────── */}
      {businessId && (
        <CommercialStrategySection
          businessId={businessId}
          currentBaselineMode={profile.commercial_baseline_mode}
          currentTriggerConfig={profile.trigger_configuration || {}}
          commercialStrategyReasoning={profile.commercial_strategy_reasoning}
          triggerUpdatedBy={profile.trigger_updated_by}
        />
      )}

    </div>
  );
}


