import { useState } from 'react';
import { useTranslation } from 'react-i18next';

interface IdentitySectionProps {
  profile: {
    brand_essence?: string;
    positioning?: string;
    core_values?: string[];
    what_makes_us_different?: string;
    identity_confidence?: number;
    identity_reasoning?: string;
  };
}

export function IdentitySection({ profile }: IdentitySectionProps) {
  const { t } = useTranslation();
  const [showReasoning, setShowReasoning] = useState(false);

  const getConfidenceStars = (confidence?: number) => {
    if (!confidence) return '';
    const stars = Math.round(confidence * 5);
    return '⭐'.repeat(stars);
  };

  const getConfidenceColor = (confidence?: number) => {
    if (!confidence) return 'text-gray-500';
    if (confidence >= 0.85) return 'text-green-600';
    if (confidence >= 0.70) return 'text-yellow-600';
    return 'text-orange-600';
  };

  return (
    <div className="border border-blue-300 rounded-lg overflow-hidden bg-blue-50/30">
      {/* Header */}
      <div className="bg-blue-50 px-4 py-3 border-b border-blue-200">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-bold text-blue-900">🆕 IDENTITET</h2>
          {profile.identity_confidence !== undefined && (
            <div className="flex items-center gap-2">
              <span className="text-sm">{getConfidenceStars(profile.identity_confidence)}</span>
              <span className={`text-sm font-medium ${getConfidenceColor(profile.identity_confidence)}`}>
                {(profile.identity_confidence * 100).toFixed(0)}% confidence
              </span>
            </div>
          )}
        </div>
        <p className="text-xs text-blue-700 mt-1">
          Business-level identity generated by AI from menu, location, and programmes
        </p>
      </div>

      {/* Content */}
      <div className="p-4 space-y-6">
        {/* Brand Essence */}
        {profile.brand_essence && (
          <div>
            <h3 className="text-sm font-bold uppercase text-gray-700 mb-2">{t('brandProfileV5.brandEssence')}</h3>
            <p className="text-base leading-relaxed">{profile.brand_essence}</p>
          </div>
        )}

        {/* Positioning */}
        {profile.positioning && (
          <div>
            <h3 className="text-sm font-bold uppercase text-gray-700 mb-2">{t('brandProfileV5.positioning')}</h3>
            <p className="text-base leading-relaxed">{profile.positioning}</p>
          </div>
        )}

        {/* Core Values */}
        {profile.core_values && profile.core_values.length > 0 && (
          <div>
            <h3 className="text-sm font-bold uppercase text-gray-700 mb-2">{t('brandProfileV5.coreValues')}</h3>
            <ul className="space-y-2">
              {profile.core_values.map((value, index) => (
                <li key={index} className="flex items-start gap-2">
                  <span className="text-blue-500 mt-1 shrink-0">•</span>
                  <span className="text-base">{value}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* What Makes Us Different */}
        {profile.what_makes_us_different && (
          <div>
            <h3 className="text-sm font-bold uppercase text-gray-700 mb-2">{t('brandProfileV5.whatMakesUsDifferent')}</h3>
            <p className="text-base leading-relaxed font-medium text-blue-900">
              {profile.what_makes_us_different}
            </p>
          </div>
        )}

        {/* AI Reasoning (collapsible) */}
        {profile.identity_reasoning && (
          <div className="border-t border-blue-200 pt-4">
            <button
              onClick={() => setShowReasoning(!showReasoning)}
              className="flex items-center gap-2 text-sm font-medium text-blue-700 hover:text-blue-900 transition-colors"
            >
              <span>{showReasoning ? '▼' : '▶'}</span>
              <span>{t('brandProfileV5.viewAiReasoning')}</span>
            </button>
            {showReasoning && (
              <div className="mt-3 p-3 bg-blue-100 rounded text-sm text-gray-700 leading-relaxed">
                {profile.identity_reasoning}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
