// Brand Profile V5 Type Definitions
// Layer 3 (Identity Profile) + Layer 4 (Audience Segments)

/**
 * Layer 3: Identity Profile
 * Stored in business_brand_profile table
 * Generated by brand-profile-generator-v5
 */
export interface IdentityProfile {
  brand_essence: string
  positioning: string
  core_values: string[]  // Array of "Title - Description" strings
  what_makes_us_different: string
  identity_confidence: number  // 0-1
  identity_reasoning?: string  // AI explanation for identity decisions
  local_location_reference?: string  // e.g., "ved åen"
}

/**
 * Layer 4: Audience Segment
 * Stored in business_programme_profiles.audience_segments JSONB
 * Programme-specific audience targeting
 */
export interface AudienceSegment {
  label: string  // e.g., "Weekend-brunch-gæster", "Frokost-pendlere"
  timing_windows: string[]  // e.g., ["Lør-Søn 10:00-14:00"]
  content_angles: string[]  // e.g., ["Social brunch-oplevelse", "Menu variation"]
  segment_size: 'primary' | 'secondary' | 'niche'
  motivation: 'social_gathering' | 'convenience' | 'experience_seeking' | 'routine'
  decision_timing: 'spontaneous' | 'planned' | 'mixed'
  goal_contribution: 'drive_footfall' | 'strengthen_brand' | 'retain_regulars'
  evidence: string[]  // Proof from database (e.g., ["Menu has børneportioner"])
}

/**
 * Programme Profile (contains segments)
 * Stored in business_programme_profiles table
 */
export interface ProgrammeProfile {
  programme_type: string  // "brunch", "lunch", "dinner", "bar"
  programme_name: string  // Display name
  audience_segments: AudienceSegment[]
  segment_confidence?: number  // 0-1
  segment_reasoning?: string
}

/**
 * Timing Window Parser Result
 * Used by getActiveSegment to match current time to segment
 */
export interface ParsedTimingWindow {
  startDay: number  // 0-6 (Sun-Sat)
  endDay: number
  startHour: number  // 0-23
  endHour: number
  daysOfWeek: number[]  // [1,2,3,4,5] for Mon-Fri
  rawString: string  // Original input for debugging
}

/**
 * Active Segment Match Result
 * Returned by getActiveSegment()
 */
export interface ActiveSegmentMatch {
  programme: ProgrammeProfile
  segment: AudienceSegment
  matchConfidence: number  // 0-1
  matchReason: string
}

/**
 * V5 Integration Metadata
 * Added to weekly strategy output for tracking
 */
export interface V5Metadata {
  v5_enabled: boolean
  layer3_used: boolean
  layer4_used: boolean
  evidence_validation_enabled: boolean
  segments_matched: number
  fallback_reason?: string
}

/**
 * Validation Result
 * Used by evidence validators and segment matchers
 */
export interface ValidationResult {
  valid: boolean
  warnings: string[]
  errors: string[]
  confidence?: number
}

/**
 * Slot Assignment (Phase 1 integration)
 * Maps weekly plan slots (A/B/C/D) to audience segments
 */
export interface SlotAssignment {
  slot: 'A' | 'B' | 'C' | 'D'
  programme?: ProgrammeProfile
  segment?: AudienceSegment
  confidence: number
  reason: string
}

/**
 * V5 Data Quality Assessment
 * Used by audit scripts
 */
export interface V5DataQuality {
  businessId: string
  businessName: string
  hasLayer3: boolean
  layer3Completeness: number  // 0-1 (% of fields populated)
  layer3Fields: {
    brand_essence: boolean
    positioning: boolean
    core_values: boolean
    what_makes_us_different: boolean
    identity_confidence: number
  }
  hasLayer4: boolean
  layer4Programmes: number
  totalSegments: number
  segmentsWithEvidence: number
  averageSegmentConfidence: number
  quality: 'ready' | 'partial' | 'missing' | 'error'
  missingFields: string[]
  recommendations: string[]
}
