import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const supabase = createClient(
  Deno.env.get('VITE_SUPABASE_URL')!,
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
);

const { data } = await supabase
  .from('weekly_strategies')
  .select('target_post_count, strategic_brief_raw')
  .eq('business_id', '2037d63c-a138-4247-89c5-5b6b8cef9f3f')
  .eq('week_number', 20)
  .single();

console.log('Target post count:', data?.target_post_count);

// Parse raw output to see what AI generated
if (data?.strategic_brief_raw) {
  const raw = JSON.parse(data.strategic_brief_raw);
  console.log('Angles generated by AI:', raw.angles?.length);
}
