-- Add voice_examples column to business_brand_profile table
-- This column stores voice examples and vocabulary preferences
-- Generated by Brand Profile Generator v3.4

-- Add the new column
ALTER TABLE business_brand_profile
ADD COLUMN IF NOT EXISTS voice_examples JSONB DEFAULT NULL;

-- Add comment for documentation
COMMENT ON COLUMN business_brand_profile.voice_examples IS 'Voice examples and vocabulary: do_say (example phrases), dont_say (anti-patterns), vocabulary (prefer/avoid word lists)';

-- Example structure:
-- {
--   "do_say": [
--     "Kom forbi til en kop kaffe og hjemmebagt kage",
--     "Søndagsbrunch med udsigt over søen",
--     "Vi glæder os til at se dig"
--   ],
--   "dont_say": [
--     "Check out our new drops",
--     "Unikke kulinariske oplevelser",
--     "Premium quality experience"
--   ],
--   "vocabulary": {
--     "prefer": ["gæster", "hjemmelavet", "frisk", "lokale", "hyggelig"],
--     "avoid": ["kunder", "premium", "eksklusive", "vibes", "experience"]
--   }
-- }
