-- Migration: Add business_character column to business_brand_profile
-- 
-- business_character is a plain-text, 1–2 sentence AI-generated description of
-- what the business actually is (type, format, hybrid concept, defining character).
-- Generated by Prompt B in brand-profile-generator and consumed by
-- WeekContext.business_character to drive Phase 1 & Phase 2 strategy prompts,
-- replacing the deprecated hard-coded business_type framework/alias system.
--
-- Example value:
--   "Café og naturvinbar der åbner som kaffebar om morgenen og skifter til vinbar om aftenen."

ALTER TABLE business_brand_profile
  ADD COLUMN IF NOT EXISTS business_character TEXT;

COMMENT ON COLUMN business_brand_profile.business_character IS
  'AI-generated plain-text (1–2 sentences) describing what this business actually is: '
  'type, format, hybrid concept, defining character. '
  'Consumed by WeekContext.business_character in get-weekly-strategy. '
  'Generated by brand-profile-generator Prompt B. Added 2026.';
