-- ADD_VOICE_RATIONALE_COLUMN.sql
-- Adds voice_rationale to business_brand_profile
--
-- Purpose: Store the AI's plain-Danish explanation of HOW the Voice rules were derived:
--   - which signals were available (website copy quality, menu character, location anchor,
--     price register, occasion arc, audience signals)
--   - whether rules come from OBSERVED text patterns (Path A) or are INFERRED from
--     situational signals (Path B)
--   - why this Voice fits this specific business over a generic one
--
-- This field is shown to the business owner as the rationale behind their Voice profile.
-- Generated by Prompt B, written before tone_of_voice rules are derived.
--
-- Run this in Supabase SQL Editor (Settings → SQL Editor)
-- ============================================================

ALTER TABLE business_brand_profile
  ADD COLUMN IF NOT EXISTS voice_rationale TEXT DEFAULT NULL;

COMMENT ON COLUMN business_brand_profile.voice_rationale IS
  'Plain-Danish rationale (3–6 sentences) explaining how the Voice rules were derived. '
  'Covers signal sources, evidence quality (observed vs. assessed), and why this specific '
  'Voice fits this business. Generated by brand-profile-generator Prompt B.';
