-- Add social_style column to business_brand_profile table
-- This column stores emoji usage preferences and hashtag strategy
-- Generated by Brand Profile Generator v3.3

-- Add the new column
ALTER TABLE business_brand_profile
ADD COLUMN IF NOT EXISTS social_style JSONB DEFAULT NULL;

-- Add comment for documentation
COMMENT ON COLUMN business_brand_profile.social_style IS 'Social media style preferences: emoji_usage (none/minimal/moderate/expressive), emoji_examples (array), hashtag_strategy (branded/category/local arrays)';

-- Example structure:
-- {
--   "emoji_usage": "moderate",
--   "emoji_examples": ["☕", "🥐", "🌿", "✨"],
--   "hashtag_strategy": {
--     "branded": ["#CafeNavn", "#NysgerigKaffe"],
--     "category": ["#brunch", "#kaffe", "#cafe"],
--     "local": ["#aarhus", "#midtbyen", "#aarhuscafe"]
--   }
-- }
