-- Add posting_strategy and busy_pattern to business_brand_profile
-- Generated by brand-profile-generator Stage PS (AI-assessed once per business)
-- Consumed by get-weekly-strategy business-rules-engine for slot window determination

ALTER TABLE business_brand_profile
  ADD COLUMN IF NOT EXISTS posting_strategy jsonb,
  ADD COLUMN IF NOT EXISTS busy_pattern jsonb;

COMMENT ON COLUMN business_brand_profile.posting_strategy IS
  'AI-generated optimal weekly posting strategy: booking_model_type, slot_windows (footfall/brand/loyalty), cta_emphasis, rationale. Set once during brand profile generation.';

COMMENT ON COLUMN business_brand_profile.busy_pattern IS
  'AI-assessed typical busy/quiet pattern: weekly_pattern (busiest/quietest days), seasonal_peaks/valleys, monthly_pattern, holiday_impact. Set once during brand profile generation.';
