-- Add location_strategy column to business_brand_profile
-- Migration for Instruction C: Wire Location Strategy into Brand Profile Pipeline
-- Created: 2026-06-26

ALTER TABLE business_brand_profile
ADD COLUMN IF NOT EXISTS location_strategy JSONB DEFAULT NULL;

COMMENT ON COLUMN business_brand_profile.location_strategy IS 
'Location strategy output: reachable demographics (filtered by price/booking), positioning angles, content triggers, and competitive gap analysis. Generated by location-strategy.ts module.';
