-- =====================================================
-- LAYER 4: PERFORMANCE TRACKING & OPTIMIZATION
-- =====================================================
-- Infrastructure for learning from post performance
-- Tables will be empty until API integration feeds data
-- Once data flows in, optimization automatically activates

-- =====================================================
-- HELPER FUNCTION FOR TRIGGERS
-- =====================================================
-- Function to automatically update updated_at timestamp

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- PERFORMANCE LOG TABLE
-- =====================================================
-- Stores actual performance metrics from Instagram/Facebook

CREATE TABLE IF NOT EXISTS content_performance_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  
  -- Link to original post idea (if generated by system)
  -- Note: No FK constraint - post_ideas table may not exist in all deployments
  post_idea_id UUID,
  
  -- Content classification
  content_type TEXT, -- 'menu_highlight', 'atmosphere_experience', etc.
  content_pillar TEXT, -- From brand_profile.content_pillars
  business_type TEXT, -- FSE, SBO, MFV, MFD, QSR
  
  -- Platform & timing
  platform TEXT NOT NULL CHECK (platform IN ('instagram', 'facebook', 'both')),
  posted_at TIMESTAMPTZ NOT NULL,
  post_time TIME, -- Extract from posted_at for time-of-day analysis
  post_day_of_week INTEGER, -- 0=Sunday, 6=Saturday
  
  -- Performance metrics (from platform API)
  reach INTEGER DEFAULT 0,
  impressions INTEGER DEFAULT 0,
  engagement_total INTEGER DEFAULT 0, -- Sum of interactions
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  saves INTEGER DEFAULT 0, -- Instagram saves/"bookmarks"
  clicks INTEGER DEFAULT 0, -- Link clicks
  
  -- Calculated metrics
  engagement_rate DECIMAL(5,2) GENERATED ALWAYS AS (
    CASE 
      WHEN reach > 0 THEN (engagement_total::DECIMAL / reach * 100)
      ELSE 0 
    END
  ) STORED,
  
  click_through_rate DECIMAL(5,2) GENERATED ALWAYS AS (
    CASE 
      WHEN impressions > 0 THEN (clicks::DECIMAL / impressions * 100)
      ELSE 0 
    END
  ) STORED,
  
  -- Context (for learning patterns)
  menu_items_featured TEXT[], -- Which dishes were shown
  location_hooks TEXT[], -- Which location features mentioned
  weather_condition TEXT, -- 'sunny', 'rainy', 'cold', etc.
  -- Note: No FK constraint - contextual_calendar may not exist in all deployments
  calendar_event_id UUID,
  seasonal_context TEXT, -- 'spring', 'summer', 'autumn', 'winter'
  
  -- Quality indicators
  was_ai_generated BOOLEAN DEFAULT TRUE,
  user_edited BOOLEAN DEFAULT FALSE,
  visual_style TEXT, -- 'food_closeup', 'atmosphere', 'people', 'action'
  
  -- User feedback (optional)
  user_rating INTEGER CHECK (user_rating BETWEEN 1 AND 5),
  user_notes TEXT,
  
  -- Metadata
  fetched_at TIMESTAMPTZ DEFAULT NOW(), -- When we fetched metrics from API
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT valid_engagement CHECK (engagement_total >= 0),
  CONSTRAINT valid_reach CHECK (reach >= 0)
);

-- Indexes for performance queries
CREATE INDEX idx_perf_log_business ON content_performance_log(business_id);
CREATE INDEX idx_perf_log_posted_at ON content_performance_log(posted_at DESC);
CREATE INDEX idx_perf_log_content_type ON content_performance_log(content_type);
CREATE INDEX idx_perf_log_platform ON content_performance_log(platform);
CREATE INDEX idx_perf_log_engagement_rate ON content_performance_log(engagement_rate DESC);

-- Composite indexes for common queries
CREATE INDEX idx_perf_log_business_type ON content_performance_log(business_id, content_type);
CREATE INDEX idx_perf_log_business_date ON content_performance_log(business_id, posted_at DESC);

-- Trigger for updated_at
CREATE TRIGGER update_perf_log_updated_at
  BEFORE UPDATE ON content_performance_log
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- CONTENT TYPE BASELINES TABLE
-- =====================================================
-- Stores calculated performance baselines per business

CREATE TABLE IF NOT EXISTS content_type_baselines (
  business_id UUID PRIMARY KEY REFERENCES businesses(id) ON DELETE CASCADE,
  
  -- Overall business performance
  overall_avg_engagement_rate DECIMAL(5,2) DEFAULT 0,
  overall_avg_reach INTEGER DEFAULT 0,
  total_posts_analyzed INTEGER DEFAULT 0,
  
  -- Per content type baselines
  baselines JSONB DEFAULT '{}'::jsonb,
  -- Format:
  -- {
  --   "menu_highlight": {
  --     "avg_engagement_rate": 3.2,
  --     "avg_reach": 1200,
  --     "sample_size": 45,
  --     "best_time": "10:30",
  --     "best_day": 5,
  --     "top_performing_dishes": ["Burger", "Ribeye"],
  --     "variance": 0.8
  --   },
  --   "atmosphere_experience": {...}
  -- }
  
  -- Per platform baselines
  platform_baselines JSONB DEFAULT '{}'::jsonb,
  -- Format:
  -- {
  --   "instagram": {
  --     "avg_engagement_rate": 4.1,
  --     "avg_reach": 1300,
  --     "best_posting_times": ["09:00", "13:00", "18:00"],
  --     "best_days": [5, 6] // Friday, Saturday
  --   },
  --   "facebook": {...}
  -- }
  
  -- Learning status
  sufficient_data BOOLEAN DEFAULT FALSE, -- TRUE when sample_size >= 20
  last_calculated TIMESTAMPTZ,
  
  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger for updated_at
CREATE TRIGGER update_baselines_updated_at
  BEFORE UPDATE ON content_type_baselines
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- BASELINE CALCULATION FUNCTION
-- =====================================================
-- Recalculates baselines from performance log

CREATE OR REPLACE FUNCTION calculate_content_baselines(p_business_id UUID)
RETURNS JSONB AS $$
DECLARE
  v_overall_avg_engagement DECIMAL(5,2);
  v_overall_avg_reach INTEGER;
  v_total_posts INTEGER;
  v_baselines JSONB := '{}'::jsonb;
  v_platform_baselines JSONB := '{}'::jsonb;
  v_content_type TEXT;
  v_platform TEXT;
  v_sufficient_data BOOLEAN := FALSE;
BEGIN
  -- Get overall stats (last 90 days)
  SELECT 
    COALESCE(AVG(engagement_rate), 0),
    COALESCE(AVG(reach), 0)::INTEGER,
    COUNT(*)
  INTO v_overall_avg_engagement, v_overall_avg_reach, v_total_posts
  FROM content_performance_log
  WHERE business_id = p_business_id
    AND posted_at >= NOW() - INTERVAL '90 days';
  
  -- Check if we have sufficient data
  v_sufficient_data := v_total_posts >= 20;
  
  -- Calculate per content type baselines
  FOR v_content_type IN 
    SELECT DISTINCT content_type 
    FROM content_performance_log 
    WHERE business_id = p_business_id 
      AND content_type IS NOT NULL
      AND posted_at >= NOW() - INTERVAL '90 days'
  LOOP
    v_baselines := v_baselines || jsonb_build_object(
      v_content_type,
      (
        SELECT jsonb_build_object(
          'avg_engagement_rate', COALESCE(AVG(engagement_rate), 0),
          'avg_reach', COALESCE(AVG(reach), 0)::INTEGER,
          'sample_size', COUNT(*),
          'best_time', (
            SELECT post_time::TEXT
            FROM content_performance_log
            WHERE business_id = p_business_id 
              AND content_type = v_content_type
              AND post_time IS NOT NULL
            ORDER BY engagement_rate DESC
            LIMIT 1
          ),
          'best_day', (
            SELECT post_day_of_week
            FROM content_performance_log
            WHERE business_id = p_business_id 
              AND content_type = v_content_type
              AND post_day_of_week IS NOT NULL
            GROUP BY post_day_of_week
            ORDER BY AVG(engagement_rate) DESC
            LIMIT 1
          ),
          'top_performing_items', (
            SELECT COALESCE(jsonb_agg(DISTINCT item), '[]'::jsonb)
            FROM (
              SELECT unnest(menu_items_featured) AS item
              FROM content_performance_log
              WHERE business_id = p_business_id 
                AND content_type = v_content_type
                AND menu_items_featured IS NOT NULL
              ORDER BY engagement_rate DESC
              LIMIT 5
            ) items
          ),
          'variance', COALESCE(STDDEV(engagement_rate), 0)
        )
        FROM content_performance_log
        WHERE business_id = p_business_id 
          AND content_type = v_content_type
          AND posted_at >= NOW() - INTERVAL '90 days'
      )
    );
  END LOOP;
  
  -- Calculate per platform baselines
  FOR v_platform IN 
    SELECT DISTINCT platform 
    FROM content_performance_log 
    WHERE business_id = p_business_id
      AND posted_at >= NOW() - INTERVAL '90 days'
  LOOP
    v_platform_baselines := v_platform_baselines || jsonb_build_object(
      v_platform,
      (
        SELECT jsonb_build_object(
          'avg_engagement_rate', COALESCE(AVG(engagement_rate), 0),
          'avg_reach', COALESCE(AVG(reach), 0)::INTEGER,
          'sample_size', COUNT(*),
          'best_posting_times', (
            SELECT jsonb_agg(DISTINCT post_time::TEXT)
            FROM (
              SELECT post_time
              FROM content_performance_log
              WHERE business_id = p_business_id 
                AND platform = v_platform
                AND post_time IS NOT NULL
              ORDER BY engagement_rate DESC
              LIMIT 3
            ) times
          ),
          'best_days', (
            SELECT jsonb_agg(DISTINCT day)
            FROM (
              SELECT post_day_of_week AS day
              FROM content_performance_log
              WHERE business_id = p_business_id 
                AND platform = v_platform
                AND post_day_of_week IS NOT NULL
              GROUP BY post_day_of_week
              ORDER BY AVG(engagement_rate) DESC
              LIMIT 3
            ) days
          )
        )
        FROM content_performance_log
        WHERE business_id = p_business_id 
          AND platform = v_platform
          AND posted_at >= NOW() - INTERVAL '90 days'
      )
    );
  END LOOP;
  
  -- Upsert into baselines table
  INSERT INTO content_type_baselines (
    business_id,
    overall_avg_engagement_rate,
    overall_avg_reach,
    total_posts_analyzed,
    baselines,
    platform_baselines,
    sufficient_data,
    last_calculated
  )
  VALUES (
    p_business_id,
    v_overall_avg_engagement,
    v_overall_avg_reach,
    v_total_posts,
    v_baselines,
    v_platform_baselines,
    v_sufficient_data,
    NOW()
  )
  ON CONFLICT (business_id) 
  DO UPDATE SET
    overall_avg_engagement_rate = EXCLUDED.overall_avg_engagement_rate,
    overall_avg_reach = EXCLUDED.overall_avg_reach,
    total_posts_analyzed = EXCLUDED.total_posts_analyzed,
    baselines = EXCLUDED.baselines,
    platform_baselines = EXCLUDED.platform_baselines,
    sufficient_data = EXCLUDED.sufficient_data,
    last_calculated = EXCLUDED.last_calculated;
  
  -- Return calculated baselines for inspection
  RETURN jsonb_build_object(
    'overall_avg_engagement_rate', v_overall_avg_engagement,
    'overall_avg_reach', v_overall_avg_reach,
    'total_posts_analyzed', v_total_posts,
    'sufficient_data', v_sufficient_data,
    'baselines', v_baselines,
    'platform_baselines', v_platform_baselines
  );
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- PERFORMANCE-ADJUSTED DISTRIBUTION
-- =====================================================
-- Adjusts Layer 2 content distribution based on performance

CREATE OR REPLACE FUNCTION get_performance_adjusted_distribution(
  p_business_id UUID,
  p_business_type TEXT
)
RETURNS TABLE (
  content_type TEXT,
  baseline_percentage DECIMAL,
  adjusted_percentage DECIMAL,
  adjustment_reason TEXT,
  priority INTEGER
) AS $$
DECLARE
  v_baselines RECORD;
  v_type_baseline JSONB;
  v_overall_avg DECIMAL;
  v_type_avg DECIMAL;
  v_variance DECIMAL;
  v_adjustment DECIMAL;
BEGIN
  -- Get baselines for this business
  SELECT * INTO v_baselines
  FROM content_type_baselines
  WHERE business_id = p_business_id;
  
  -- If no baselines yet (insufficient data), return Layer 2 defaults
  IF NOT FOUND OR NOT v_baselines.sufficient_data THEN
    RETURN QUERY
    SELECT 
      cdr.content_type_id,
      cdr.baseline_percentage,
      cdr.baseline_percentage AS adjusted_percentage,
      'Using default baseline (insufficient performance data)' AS adjustment_reason,
      cdr.priority
    FROM content_distribution_rules cdr
    WHERE cdr.business_type = p_business_type
    ORDER BY cdr.priority DESC;
    RETURN;
  END IF;
  
  v_overall_avg := v_baselines.overall_avg_engagement_rate;
  
  -- Return adjusted distribution for each content type
  RETURN QUERY
  SELECT 
    cdr.content_type_id,
    cdr.baseline_percentage,
    CASE
      -- If type performs well, increase by up to 20%
      WHEN (v_baselines.baselines->>cdr.content_type_id->'avg_engagement_rate')::DECIMAL > v_overall_avg * 1.3
        THEN LEAST(cdr.baseline_percentage * 1.2, 50.0)
      
      -- If type performs slightly above average, increase by 10%
      WHEN (v_baselines.baselines->>cdr.content_type_id->'avg_engagement_rate')::DECIMAL > v_overall_avg * 1.1
        THEN LEAST(cdr.baseline_percentage * 1.1, 45.0)
      
      -- If type performs slightly below average, decrease by 10%
      WHEN (v_baselines.baselines->>cdr.content_type_id->'avg_engagement_rate')::DECIMAL < v_overall_avg * 0.9
        THEN GREATEST(cdr.baseline_percentage * 0.9, 5.0)
      
      -- If type performs poorly, decrease by 20%
      WHEN (v_baselines.baselines->>cdr.content_type_id->'avg_engagement_rate')::DECIMAL < v_overall_avg * 0.7
        THEN GREATEST(cdr.baseline_percentage * 0.8, 5.0)
      
      -- Otherwise, keep baseline
      ELSE cdr.baseline_percentage
    END AS adjusted_percentage,
    
    CASE
      WHEN (v_baselines.baselines->>cdr.content_type_id->'avg_engagement_rate')::DECIMAL > v_overall_avg * 1.3
        THEN 'High performer (+30% above average) → Increased frequency'
      WHEN (v_baselines.baselines->>cdr.content_type_id->'avg_engagement_rate')::DECIMAL > v_overall_avg * 1.1
        THEN 'Above average performer → Increased frequency'
      WHEN (v_baselines.baselines->>cdr.content_type_id->'avg_engagement_rate')::DECIMAL < v_overall_avg * 0.7
        THEN 'Poor performer (-30% below average) → Decreased frequency'
      WHEN (v_baselines.baselines->>cdr.content_type_id->'avg_engagement_rate')::DECIMAL < v_overall_avg * 0.9
        THEN 'Below average performer → Decreased frequency'
      ELSE 'Performance within normal range → Baseline maintained'
    END AS adjustment_reason,
    
    cdr.priority
  FROM content_distribution_rules cdr
  WHERE cdr.business_type = p_business_type
  ORDER BY cdr.priority DESC;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- HELPER FUNCTIONS FOR API INTEGRATION
-- =====================================================

-- Function to update post_ideas with performance data
-- (Called by API integration after fetching from Instagram/Facebook)
-- Note: This function is a placeholder - only use if post_ideas table exists
CREATE OR REPLACE FUNCTION update_post_performance(
  p_post_idea_id UUID,
  p_reach INTEGER,
  p_engagement INTEGER,
  p_clicks INTEGER DEFAULT 0
)
RETURNS VOID AS $$
BEGIN
  -- Check if post_ideas table exists before updating
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'post_ideas') THEN
    EXECUTE format(
      'UPDATE post_ideas SET reach = %L, engagement = %L, clicks = %L, updated_at = NOW() WHERE id = %L',
      p_reach, p_engagement, p_clicks, p_post_idea_id
    );
  END IF;
  
  -- Trigger baseline recalculation if significant data added
  -- (Will be called by background job)
END;
$$ LANGUAGE plpgsql;

-- Function to log performance from API
CREATE OR REPLACE FUNCTION log_post_performance(
  p_business_id UUID,
  p_post_idea_id UUID,
  p_content_type TEXT,
  p_platform TEXT,
  p_posted_at TIMESTAMPTZ,
  p_reach INTEGER,
  p_engagement INTEGER,
  p_likes INTEGER DEFAULT 0,
  p_comments INTEGER DEFAULT 0,
  p_shares INTEGER DEFAULT 0,
  p_saves INTEGER DEFAULT 0,
  p_clicks INTEGER DEFAULT 0
)
RETURNS UUID AS $$
DECLARE
  v_log_id UUID;
  v_business_type TEXT;
BEGIN
  -- Get business type
  SELECT bo.establishment_type INTO v_business_type
  FROM business_operations bo
  WHERE bo.business_id = p_business_id;
  
  -- Insert performance log
  INSERT INTO content_performance_log (
    business_id,
    post_idea_id,
    content_type,
    business_type,
    platform,
    posted_at,
    post_time,
    post_day_of_week,
    reach,
    impressions,
    engagement_total,
    likes,
    comments,
    shares,
    saves,
    clicks
  )
  VALUES (
    p_business_id,
    p_post_idea_id,
    p_content_type,
    v_business_type,
    p_platform,
    p_posted_at,
    p_posted_at::TIME,
    EXTRACT(DOW FROM p_posted_at)::INTEGER,
    p_reach,
    p_reach, -- Use reach as proxy for impressions if not provided
    p_engagement,
    p_likes,
    p_comments,
    p_shares,
    p_saves,
    p_clicks
  )
  RETURNING id INTO v_log_id;
  
  RETURN v_log_id;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- COMMENTS
-- =====================================================

COMMENT ON TABLE content_performance_log IS 'Historical post performance data from Instagram/Facebook APIs - feeds learning system';
COMMENT ON TABLE content_type_baselines IS 'Calculated performance baselines per business - auto-updated as data flows in';
COMMENT ON FUNCTION calculate_content_baselines IS 'Recalculates baselines from last 90 days of performance data - run after new data added';
COMMENT ON FUNCTION get_performance_adjusted_distribution IS 'Returns Layer 2 distribution adjusted by actual performance - replaces static baselines when data exists';
COMMENT ON FUNCTION log_post_performance IS 'Insert performance metrics from API - called by Instagram/Facebook integration';
COMMENT ON COLUMN content_performance_log.engagement_rate IS 'Auto-calculated: (engagement / reach) * 100';
COMMENT ON COLUMN content_performance_log.click_through_rate IS 'Auto-calculated: (clicks / impressions) * 100';
COMMENT ON COLUMN content_type_baselines.sufficient_data IS 'TRUE when >= 20 posts analyzed - enables performance-based adjustments';

-- =====================================================
-- INITIAL STATE
-- =====================================================
-- Tables are created but empty
-- Baselines will show "insufficient data" until API integration feeds metrics
-- System gracefully degrades to Layer 2 static baselines until then
