-- Layer 3: Add positioning column for brand identity
-- Migration for programme-aware brand profile system
-- Date: May 6, 2026

-- Add positioning column (Layer 3 competitive differentiation)
ALTER TABLE business_brand_profile
ADD COLUMN IF NOT EXISTS positioning TEXT DEFAULT NULL;

-- Add comment for documentation
COMMENT ON COLUMN business_brand_profile.positioning IS 
'Layer 3: Business-level competitive differentiation (2-3 sentences). 
Generated by identity-profile.ts AI module. 
Example: "Vi er den eneste café i Nyhavn med både traditionel dansk morgenmad og autentisk italiensk pasta."';

-- Note: Other Layer 3 fields use existing columns:
-- - brand_essence (already exists)
-- - values (already exists, will store core_values)
-- - what_makes_us_different (already exists)
