-- Migration: add owner_document column to business_brand_profile
-- Contains the human-readable brand profile summary (brand_feel, tone_sentence, usps, audience, caption_examples)
-- Generated by Stage B4 (synthesiseOwnerDocument) in brand-profile-generator
-- Nullable: old profiles remain null until regenerated

ALTER TABLE business_brand_profile
  ADD COLUMN IF NOT EXISTS owner_document JSONB;

COMMENT ON COLUMN business_brand_profile.owner_document IS
  'Human-readable brand profile summary for owner display. JSON shape: {brand_feel: string, tone_sentence: string, usps: string[], audience: {primary: string, secondary: string, tertiary: string|null}, caption_examples: string[]}. Null for profiles generated before this migration.';
