ALTER TABLE business_brand_profile
  ADD COLUMN IF NOT EXISTS voice_rationale TEXT DEFAULT NULL;

COMMENT ON COLUMN business_brand_profile.voice_rationale IS
  'Plain-Danish rationale (3-6 sentences) explaining how the Voice rules were derived. '
  'Covers signal sources, evidence quality (observed vs. assessed), and why this specific '
  'Voice fits this business. Generated by brand-profile-generator Prompt B.';
